name: rakhi
favicon: null
layout_spectrum: 0.8366744173690677
typography_spectrum: 0.25253576366230845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3994345241226256
  lightness: 0.7801442083436996
  saturation: 0.9639242985285819
  rhythmicContrast: 0.5653674532659352
purpose: []
